package:
  darwin:
    tap: []
    brew:
    - lazygit
    - mise
    - nvim
    cask:
    - 1password
    - font-blex-mono-nerd-font
    - rectangle
    - wezterm
    mas:
    - id: "1569813296"
      name: 1Password for Safari
